--- /usr/src/linux-6.10.6-noalexan/Makefile	2024-08-22 01:31:03.752189207 +0200
+++ Makefile	2024-08-22 02:55:32.236167294 +0200
@@ -2,7 +2,7 @@
 VERSION = 6
 PATCHLEVEL = 10
 SUBLEVEL = 6
-EXTRAVERSION =
+EXTRAVERSION = -thor_kernel
 NAME = Baby Opossum Posse
 
 # *DOCUMENTATION*
